### ISSUE TITLE
Account Management Tab - information entry

### ISSUE THREAD

**Issue by shlokpatel16** [MirroredNova/StockCheck#28]
Description:
I went to change some information and was able to successfully change my name to "%%%%%" and my phone number to a number with 12 digits.

Severity: Trivial, this is just going to be related to how competent and accurate the user provided information is. I did not run into any issues where this broke the program, but a safety measure.

Suggestions: Do some user input checking so that they are not allowed to enter wrong/potentially malice information

**Comment by MirroredNova** [comment]
This is actually intended. The fields are validated, however, leniently. There are places in the world that use 12 digit phone numbers or other such combinations and given that our program isn't really dependant on personal information, the user's name fields are not restricted to any characters. We plan to leave it as is, but if issues arise, we could validate name fields to characters only.
