### ISSUE TITLE
Duplicate Stocks and Deleting stocks

### ISSUE THREAD

**Issue by shlokpatel16** [MirroredNova/StockCheck#30]
Description: I was trying to change a stock notification method , and I ended up with 3 stocks on my dashboard with the same info. 

Severity: Trivial, This is more of an annoying issue than functionality. 

Suggestions: I think you could add a way to delete stock blocks on the dashboard, or even prevent the same stock from being put up more than once. Also, maybe allowing the use to have multiple sources of notifications for the same stock without having to add multiple stock blocks to the dashboard could be cool.

**Comment by MirroredNova** [comment]
A delete and edit button has been added to the main branch as of now. May not be in the testing branch unless you pull main into it, though.
